version: '3'

services:
  pg:
    image: postgres:12
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user

  integration-test:
    depends_on:
      - pg
    image: node:14
    command:
      - /bin/bash
      - -c
      - |
        yarn
        yarn prisma migrate reset --force
        yarn test
    working_dir: '/app'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      DATABASE_URL: "postgresql://user:secret@pg:5432/test?schema=public"

volumes:
  node_modules:
